### ISSUE TITLE
Type-safe method names for createSpyForClass

### ISSUE THREAD

**Issue by shuebner** [hirezio/jasmine-auto-spies#10]
Hi,
I am using your library in a project and noticed the following:
the parameters for the names of methods returning Observables and Promises are just typed `string[]` which is error-prone.
To make full use of TypeScript I suggest typing them in a way that lets the user autocomplete the valid method names and cause compiler errors when methods are renamed without the created spies being updated.

I took the liberty of creating a PR for this.

The git precommit hook failed, though, which is why I commited without verification. So please check for any conventions I ignored.

**Comment by shairez** [comment]
Thanks @shuebner and sorry for the late late late reply (it got buried under a lot of emails). 

Originally I added this option for cases where adding the decorator wasn't possible. 
Plus, the use of `Spy<MyClass>` should catch cases where you are calling the wrong method.

I since then removed the need to use the decorator and merged it into 1 array of provided methods. 

It's mainly for use cases where something was added in the constructor like `this.someMethod = function()...` 
So I'm not sure if that can be typed as it's not part of the prototype. 

I appreciate your effort in trying to add type safety to the string names as I think it's important. 
if you see a way to still make it happen please re-open this issue and let me know, I don't mind refactor your PR myself to fit the new code.

Thanks again!

**Comment by shairez** [comment]
I thought about it again and it makes sense to add it to the existing API.

So I'll refactor your original PR and merge it

Thanks again!

**Comment by shuebner** [comment]
I am glad to contribute :-)

**Comment by shairez** [comment]
closed by #11 

Thanks again @shuebner
