### ISSUE TITLE
Readme should explain benefits over jasmine.createSpyObj

### ISSUE THREAD

**Issue by kbirger** [hirezio/jasmine-auto-spies#8]
I came here from a post by the maintainer on an ngx-translate issue. I came here looking for an explanation of the concern in the title. 

I still don't see what benefits this has, other than perhaps mocking all properties by default (not actually sure).

In any event, please improve the documentation to cover items such as this.

**Comment by shairez** [comment]
Sorry for the late late late response :)
`createSpyObj` forces you to manually add the method names as strings.

This library scans your class and figure out the method names automatically. 

By that it provides also type safety in case of future code refactoring. 

Plus, it adds the ability to return fake promises / emit fake observable values by inferring your method's return type... so that's another thing createSpyObj doesn't do.
